### ISSUE TITLE
Gracefully handle Database connection timeouts

### ISSUE THREAD

**Issue by guidospadotto-profesia** [CloudOpting/cloudopting-manager#104]
Investigate and fix the scenario in which the Activiti engine "goes crazy" because the underlying Database connection has been closed.

**Comment by gioppoluca** [comment]
I fear that this could hide big problems so please investigate this deeply so we get no surprises

**Comment by gioppoluca** [comment]
Can we get some feedback?

**Comment by guidospadotto-profesia** [comment]
The last answer in this thread seems interesting: https://forums.activiti.org/content/timeout-behaviour-activity-processing

**Comment by guidospadotto-profesia** [comment]
I have found this:

> "In Spring Boot, if you auto-configure Data Source, the pooling is auto-configured too if a proper Driver
> class is used (e.g. org.postgresql.Driver). You may adjust the pooling by providing the following 
> properties in application.properties: spring.datasource.test-on-borrow=true, spring.datasource.remove-
> abandoned=true, spring.datasource.validation-query=SELECT 1;"
from: [http://stackoverflow.com/questions/29620265/postgres-connection-has-been-closed-error-in-spring-boot](http://stackoverflow.com/questions/29620265/postgres-connection-has-been-closed-error-in-spring-boot) 
@cpopsa where should I set those properties?

**Comment by guidospadotto-profesia** [comment]
Might have been fixed by commit d125f8f 
Closing this issue. If it happens again, please re-open.

**Comment by gioppoluca** [comment]
Here is the error I got previous the fix commit we'll see if fixes:
[WARN] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: null
[ERROR] org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Already closed.
[ERROR] org.springframework.transaction.support.TransactionTemplate - Application exception overridden by rollback exception
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
### The error may exist in org/activiti/db/mapping/entity/Job.xml
### The error may involve org.activiti.engine.impl.persistence.entity.JobEntity.selectNextTimerJobsToExecute-Inline
### The error occurred while setting parameters
### SQL: select        RES.*             from ACT_RU_JOB RES           LEFT OUTER JOIN ACT_RU_EXECUTION PI ON PI.ID_ = RES.PROCESS_INSTANCE_ID_     where (RES.RETRIES_ > 0)       and (RES.DUEDATE_ is null or RES.DUEDATE_ <= ?)       and (RES.LOCK_OWNER_ is null or RES.LOCK_EXP_TIME_ <= ?)       and TYPE_ = 'timer'       and (           (RES.EXECUTION_ID_ is null)           or            (PI.SUSPENSION_STATE_ = 1)       )       LIMIT ? OFFSET ?
### Cause: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:107) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:98) ~[mybatis-3.2.5.jar:3.2.5]
	at org.activiti.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:435) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:426) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:421) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:408) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.persistence.entity.JobEntityManager.findNextTimerJobsToExecute(JobEntityManager.java:155) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:43) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:29) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47) ~[activiti-spring-5.18.0.jar:5.18.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) [activiti-spring-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) [activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) [activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) [activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.asyncexecutor.AcquireTimerJobsRunnable.run(AcquireTimerJobsRunnable.java:52) [activiti-engine-5.18.0.jar:5.18.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:281) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:56) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:259) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:132) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81) ~[mybatis-3.2.5.jar:3.2.5]
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104) ~[mybatis-3.2.5.jar:3.2.5]
	... 18 common frames omitted
Caused by: java.io.EOFException: null
	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:284) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1741) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[postgresql-9.3-1102-jdbc41.jar:na]
	... 31 common frames omitted
[ERROR] org.activiti.engine.impl.asyncexecutor.AcquireTimerJobsRunnable - exception during timer job acquisition: Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking
org.springframework.transaction.TransactionSystemException: Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking
	at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:548) ~[spring-orm-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processRollback(AbstractPlatformTransactionManager.java:849) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.rollback(AbstractPlatformTransactionManager.java:826) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.rollbackOnException(TransactionTemplate.java:164) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45) ~[activiti-spring-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35) ~[activiti-engine-5.18.0.jar:5.18.0]
	at org.activiti.engine.impl.asyncexecutor.AcquireTimerJobsRunnable.run(AcquireTimerJobsRunnable.java:52) ~[activiti-engine-5.18.0.jar:5.18.0]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: javax.persistence.PersistenceException: unexpected error when rollbacking
	at org.hibernate.jpa.internal.TransactionImpl.rollback(TransactionImpl.java:111) ~[hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	at org.springframework.orm.jpa.JpaTransactionManager.doRollback(JpaTransactionManager.java:544) ~[spring-orm-4.1.9.RELEASE.jar:4.1.9.RELEASE]
	... 10 common frames omitted
Caused by: org.hibernate.TransactionException: rollback failed
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:217) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.jpa.internal.TransactionImpl.rollback(TransactionImpl.java:108) ~[hibernate-entitymanager-4.3.11.Final.jar:4.3.11.Final]
	... 11 common frames omitted
Caused by: org.hibernate.TransactionException: unable to rollback against JDBC connection
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doRollback(JdbcTransaction.java:167) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.rollback(AbstractTransactionImpl.java:211) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	... 12 common frames omitted
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:843) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.rollback(AbstractJdbc2Connection.java:860) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp.DelegatingConnection.rollback(DelegatingConnection.java:368) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.rollback(PoolingDataSource.java:323) ~[commons-dbcp-1.4.jar:1.4]
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doRollback(JdbcTransaction.java:163) ~[hibernate-core-4.3.11.Final.jar:4.3.11.Final]
	... 13 common frames omitted
