### ISSUE TITLE
NullPointerException on service edit

### ISSUE THREAD

**Issue by cpopsa** [CloudOpting/cloudopting-manager#385]
Steps to reproduce:

- Go to Menu -> PUBLISH SERVICE
- Fill info in Set Global Properties screen and hit Next
- Upload items in library in Upload needed files screen and click Save (do not click Next)
- Go to Menu -> SERVICES MANAGER, find your service and click Edit
- Fill the info in Set Global Properties, Upload needed files screens
- Add TOSCA ARCHIVE and click SAVE

Result Finish button is not active, the exception is:
[ERROR] org.activiti.rest.exception.ExceptionHandlerAdvice - Unhandled exception
java.lang.NullPointerException: null
	at eu.cloudopting.bpmn.tasks.publish.update.UpdateToscaFile.execute(UpdateToscaFile.java:74) ~[classes/:na]
	at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
	at org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:101) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97) ~[activiti-engine-5.19.0.2.jar:5.19.0.2]

**Comment by ildave** [comment]
Fixed in 0afa2a903f983ea40d88fbf70d9302fb6824b0a1
